### PR TITLE
Copy .ruby-version file to Docker

### LINKED ISSUE #76: Order of `COPY` commands doesn't allow for Gemfile's `file` directive
I'm trying to use `ruby file: ".ruby-version"` on my Gemfile so I just have one file to update Ruby's version but I noticed I can't deploy on Fly with this change, I get the error that `.ruby-version` does not exist.

I noticed that `COPY --link Gemfile Gemfile.lock ./` happens before `COPY . .` so at the bundle install phase, `.ruby-version` file is not there yet. There are a couple of ways to fix this, either  put `COPY . .` before running bundle (not great) or simply copy `.ruby-version` before (or with) copying gemfile/gemfile.lock, but there's a catch: not everyone will have this file (or maybe the file is in the gitignore/dockerignore list)

thinking if this could be fixed somehow. any ideas?

### PR DESCRIPTION
**Pull request by luizkowalski**
Fixes #76

### CODE REVIEW

**Comment by luizkowalski** [comment]
I can't really see what's failing exactly, and locally, I get the weirdest behavior all the time:

```sh
❯ RAILS_ENV=test ruby test/test_sqlite3.rb
Run options: --seed 57259

# Running:
...

  1) Failure:
TestSqlite3#test_sqlite3 [/Users/luiz/Projects/dockerfile-rails/test/base.rb:51]:
--- expected
+++ actual
@@ -21,22 +21,31 @@
 "# Throw-away build stage to reduce size of final image\n" +
 "FROM base as build\n" +
 "\n" +
-"# Install packages needed to build gems\n" +
+"# Install packages needed to build gems and node modules\n" +
 "RUN apt-get update -qq && \\\n" +
-"    apt-get install --no-install-recommends -y build-essential pkg-config\n" +
+"    apt-get install --no-install-recommends -y build-essential curl node-gyp pkg-config python-is-python3\n" +
 "\n" +
+"# Install JavaScript dependencies\n" +
+"ARG NODE_VERSION=xxx\n" +
+"ARG YARN_VERSION=xxx\n" +
+"ENV PATH=/usr/local/node/bin:$PATH\n" +
+"RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \\\n" +
+"    /tmp/node-build-master/bin/node-build \"${NODE_VERSION}\" /usr/local/node && \\\n" +
+"    npm install -g yarn@$YARN_VERSION && \\\n" +
+"    rm -rf /tmp/node-build-master\n" +
+"\n" +
 "# Install application gems\n" +
 "COPY --link Gemfile Gemfile.lock .ruby-version ./\n" +
 "RUN bundle install && \\\n" +
-"    bundle exec bootsnap precompile --gemfile && \\\n" +
 "    rm -rf ~/.bundle/ \"${BUNDLE_PATH}\"/ruby/*/cache \"${BUNDLE_PATH}\"/ruby/*/bundler/gems/*/.git\n" +
 "\n" +
+"# Install node modules\n" +
+"COPY --link package.json yarn.lock ./\n" +
+"RUN yarn install --frozen-lockfile\n" +
+"\n" +
 "# Copy application code\n" +
 "COPY --link . .\n" +
 "\n" +
-"# Precompile bootsnap code for faster boot times\n" +
-"RUN bundle exec bootsnap precompile app/ lib/\n" +
-"\n" +
 "# Precompiling assets for production without requiring secret RAILS_MASTER_KEY\n" +
 "RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile\n" +
 "\n" +
```

not sure why it tries to install node

**Comment by luizkowalski** [comment]
I can't see exactly the failure, and locally the tests are passing (individually)

**Comment by rubys** [comment]
image

**Comment by luizkowalski** [comment]
Pushed the missing change, thanks!

**Comment by rubys** [comment]
I'm not enthusiastic about copying a file because it *might* be referenced by the Gemfile.  By default, new Rails 7.1 applications will have a .ruby-version file but it won't be referenced by the Gemfile.

Perhaps add something along the lines of `&& IO.read('Gemfile').include?('.ruby-version')` to `ruby_version_exists?`

**Comment by rubys** [comment]
Just to be clear: I'm not seeking perfection.  If you were to pick a new Rails project at random, it likely will have a .ruby-version file but not referenced in the Gemfile.  If the Gemfile itself contains the string ".ruby-version" it likely references that file, but only a full fledged parser would be able to determine if it actually does.

**Comment by luizkowalski** [comment]
That actually makes sense, since, IIRC, this file is ignored by default. 

I will amend the PR

**Review by rubys — APPROVED** [review]

**Comment by bradgessler** [comment]
For posterity, bundler is including a mechanism to read the .ruby-version from the Gemfile. It looks like this:

```ruby
ruby file: ".ruby-version" 
```

PR at https://github.com/rubygems/rubygems/pull/6876

**Pull request merged**
